name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .env file for Docker build
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
        echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }}" >> .env
        echo "DATABASE_URI=postgresql+psycopg2://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env

    - name: Set up .env file for frontend
      run: |
        echo "REACT_APP_SECRET_KEY=${{ secrets.SECRET_KEY }}" > frontend/.env

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: docker-compose build

    - name: Archive project directory
      run: tar -czf project.tar.gz *

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Remove old key from known_hosts
      run: |
        ssh-keygen -R ${{ secrets.VPS_HOST }}

    - name: Add VPS to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Copy project archive to VPS
      run: scp project.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/project.tar.gz

    - name: Extract project archive on VPS and set up environment
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'bash -s' <<'EOF'
        rm -rf /root/CRESSON
        mkdir -p /root/CRESSON
        tar -xzf /root/project.tar.gz -C /root/CRESSON
        rm /root/project.tar.gz
        cd /root/CRESSON
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
        echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }}" >> .env
        echo "DATABASE_URI=postgresql+psycopg2://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env
        echo "REACT_APP_SECRET_KEY=${{ secrets.SECRET_KEY }}" > frontend/.env
        docker-compose down
        docker-compose up -d
        sleep 10  # Attendre quelques secondes pour que les conteneurs démarrent
        docker-compose exec backend flask db upgrade  # Appliquer les migrations
        docker-compose logs backend
        EOF
