name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Clean npm cache and install dependencies
      run: |
        cd frontend
        npm cache clean --force
        rm -rf node_modules
        npm install

    - name: Debug - List node_modules
      run: |
        cd frontend
        ls -la node_modules

    - name: Debug - Check react-scripts
      run: |
        cd frontend
        ls -la node_modules/.bin

    - name: Build project
      run: |
        cd frontend
        npm run build

    - name: Archive build directory
      run: |
        cd frontend
        tar -czf build.tar.gz build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "194.164.72.129 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRR5bsPk+wlOCbwaSTrmYikwuxHOP0ZLxgVYZUIz7VLcAwXzy+VbEiC2OSpiz7qz2HpWCAwiOfHMs5rh5r15Lsp0QUAKHOX28DSd8EB044aQbhgHlL6m/a+HeJQbqTLSEfStwqqjjOdrRVGzHUBG8eMh57kngBDTWPTF5MXqZIopaTP5cL8VtwBULRqOAKu5PSYwhnE1CbimDyasoaRrZI3sp/0sD6Z/2/4II/PzleK6sGN+fY2Kg7pgIxYaP9Gmhn/nfSBQu29EsJE605nIr5oyLOxdN6TI5Tp5pHNlUk37axUVWnPQuhqBG51uWH976z/ZoZGVOB/MUMcQzGiS+rxBlBn95EKdhbXSPvDeX3exT+O8orJqB66YyL5gi6BlEUtzvBjvpMISH/HbNni6EcupkhPGyzpcmTDjfRQWZ/eIiQ3OFmcDYyxLupLxRAUCVITUoiGsshupRVDps/9aUPEcM2tguBXRT5BZq3Sd7MGfisOObuL7lqW2aWLAsfutc=" >> ~/.ssh/known_hosts
        echo "194.164.72.129 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHLUNnOiOrhWFLNvsctdrbBfYLW/EJ9E62qjZ7Urwq+J7KNb57q4J1AuksAnPzqwc+F4XaQyhGofbAwbB+WgFbo=" >> ~/.ssh/known_hosts
        echo "194.164.72.129 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBA1Z6txW4yD6sYZ8HK3SyzUEmIn88vD5nOPwH6nGG/a" >> ~/.ssh/known_hosts

    - name: Copy build archive to VPS
      run: |
        scp frontend/build.tar.gz root@194.164.72.129:/root/CRESSON

    - name: Extract build archive on VPS and restart Docker
      run: |
        ssh root@194.164.72.129 << 'EOF'
        if [ ! -d "/root/CRESSON" ]; then
          mkdir -p /root/CRESSON
        fi
        tar -xzf /root/CRESSON/build.tar.gz -C /root/CRESSON --strip-components=1
        rm /root/CRESSON/build.tar.gz
        cd /root/CRESSON
        docker-compose down
        docker-compose up -d
        EOF
